# mysql:
#   host: localhost
#   port: 3306
#   user: aths
#   password: jbjyaths296495
#   dbname: robot
mysql:
  host: 120.53.106.11
  port: 3306
  user: aths
  password: jbjyaths296495
  dbname: robot

system:
  auto_restart: true